<?php  //[STAMP] 14b96bc3f9e8c3e5e6d008c19c1e7960
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\CodeHelper;

trait CodeNinjaActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
